# generics is a module in DRF (rest_framework.generics) that contains pre-built generic views.
# generics gives you pre-built API views so you don’t need to write full logic yourself.
# e.g:
# CreateAPIView → for POST (create)

# ListAPIView → for GET (all items)

# RetrieveAPIView → for GET (single item)

# UpdateAPIView → for PUT/PATCH

# DestroyAPIView → for DELETE

# ListCreateAPIView → GET + POST

# RetrieveUpdateDestroyAPIView → GET + PUT + DELETE

# These generic views are built on top of GenericAPIView, which itself inherits from APIView.

# An API view is a Django view that returns JSON data instead of HTML pages.



# permissions controls who can access your API.
# DRF permission types include:

# AllowAny → anyone can access

# IsAuthenticated → only logged-in users

# IsAdminUser → only admin users

# IsAuthenticatedOrReadOnly → only logged-in users can change data
# we use these: To protect your API from unauthorized users


# RefreshToken is used to create JWT authentication tokens.
# RIt generates two tokens:
# RAccess Token (short life — like 5 minutes)

# Refresh Token (long life — like 1 day)

# permission_classes, This is an attribute you set on a view (class-based or function-based API view).

# permission_classes tells DRF which permissions to apply for this specific API view.

# CBV = class + methods handling HTTP + returning Response

# queryset → which objects to fetch

# serializer_class → how to serialize them

# APIView gives you full control, but you write more code for standard CRUD operations.

# Generics are pre-built CBVs that handle common operations automatically, so you write much less code.

# .get() is safe because if the key doesn’t exist, it returns None instead of throwing an error.

# request  contains everything about the incoming HTTP request,

# request.data contains all POST data sent by the client, usually in JSON format.

# user = authenticate(username=username, password=password)
# This is a built-in Django function that checks if a user exists with the given username and password.

#RefreshToken.for_user(user) generates a refresh token for the authenticated user.

# Refresh token can be used later to get a new access token without logging in again.

# refresh is a refresh token object generated by Simple JWT:
# refresh is a long-lasting secret token created for the user after login.
# Think of it like a key to get new keys when your short-term key expires.
# A refresh token is a long-lived JWT token used to get new access tokens without logging in again.
# str(refresh) converts the token object into a string that can be sent over HTTP.
# We use str(refresh) because the token object is a Python object, and we need a string to send it over the internet.
# Response({...}) = sending these keys to the user as JSON

# access is the short-term key (access token) that the user uses to access protected endpoints.
# refresh.access_token generates an access token from the refresh token.
# Access token = “proof that you are logged in”


# The client (frontend or mobile app) receives these tokens.

# The client stores the access token and uses it to call protected APIs.

# When the access token expires, the client uses the refresh token to get a new access token.

# This way, the user doesn’t have to login again until the refresh token expires.

# self.get_queryset() returns the queryset defined in your view.
# A queryset is basically a list of objects from the database.
# self.get_serializer() returns a serializer instance defined by serializer_class in your view.

# Protected APIs are API endpoints that require a user to be logged in or authenticated before they can access them.


# APIView is a base class for class-based views in DRF.

# It is similar to Django’s normal View, but designed specifically for building APIs.

# Provides features like:

# Handling HTTP methods (get(), post(), put(), delete(), etc.)

# Access to DRF’s request and response objects

# Support for authentication, permissions, throttling, and content negotiation



# GenericAPIView is a subclass of APIView.

# Adds built-in support for models and serializers, making it easier to write CRUD APIs.

# Often used as a base class for DRF’s generic views like:

# ListAPIView

# CreateAPIView

# RetrieveUpdateDestroyAPIView# 