# Generated by Django 5.2.1 on 2025-12-08 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
    ]
